# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
    build:
        
        working_directory: ~/repo
        
        docker:
        
        - image: circleci/openjdk:11-browsers-legacy

        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        
        - image: circleci/postgres:9.4
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: petclinic
            
        steps:
        - checkout
        
        - run:
        command: sudo -u postgres psql -p 5432 -c "create database petclinic;"
        command: sudo -u postgres psql -p 5432 -c "create user postgres with password 'postgres';"
        command: sudo -u postgres psql -p 5432 -c "grant all privileges on database petclinic to postgres;"

        # Download and cache dependencies
        
        - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "pom.xml" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run: mvn install -DskipTests

        - run: mvn dependency:go-offline

        - save_cache:
              paths:
              - ~/.m2
              key: v1-dependencies-{{ checksum "pom.xml" }}

        - run: mvn test